services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vardigo_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/app:/app/app
    restart: unless-stopped
